@startuml deployment
    !theme materia-outline
    component ControlManagment
    component ContractsManagment
    component ContractsAndRoutesReport
    component DocumentValidationSystem
    component ResourceManagement
    component MetricsManagment
    component TrainingManagment
    component TracingManagment

    node "Data Store" {
        database "Betransport_DB" {
        }
    }

    node LoginSystem [
        <b>Login system
        ----
        Initialize transportist panel
        ....
        Initialize logistic operator
        panel
        ....
        Register user       
    ]

    node TransportistPanel [
        <b>Transportist panel
        ----
        Contracts
        ....
        Control
        ....
        Documentation
        ....
        Resources
        ....
        Training
        ....
        Tracing
    ]

    node LogisticOperatorPanel [
        <b> Logistic operator panel
        ----
        Metrics
        ....
        Contracts and routes visualization
        ....
        Documents validation
    ]

    node LogoutSystem [
        <b> Logout system
        ----
        Reinitialize login system
    ]

   
    LoginSystem -[bold]-> TransportistPanel
    LoginSystem  -[bold]-> LogisticOperatorPanel

    LogisticOperatorPanel -[dashed]-> LogoutSystem
    LogisticOperatorPanel -[bold]-> ContractsAndRoutesReport
    LogisticOperatorPanel -[bold]-> DocumentValidationSystem
    LogisticOperatorPanel -[bold]-> MetricsManagment

    TransportistPanel-[bold]->ControlManagment
    TransportistPanel-[bold]->ContractsManagment
    TransportistPanel-[bold]->TrainingManagment
    TransportistPanel-[bold]->TracingManagment
    TransportistPanel-[dashed]->LogoutSystem
    TransportistPanel-[dashed]->DocumentValidationSystem
    TransportistPanel-[bold]->ResourceManagement

    ControlManagment -[bold]->Betransport_DB
    ContractsManagment -[bold]->Betransport_DB
    ContractsAndRoutesReport -[bold]->Betransport_DB
    DocumentValidationSystem -[bold]->Betransport_DB
    MetricsManagment -[bold]->Betransport_DB
    ResourceManagement -[bold]->Betransport_DB
    TracingManagment -[bold]->Betransport_DB
    TrainingManagment -[bold]->Betransport_DB


@enduml