@startuml classes
    enum OrganizationType {
        OPERATING_COMPANIES
        TRANSPORTIST_COMPANIES
    }
    
    class Application {
        Integer id
        Integer carId
        Integer operatorId
        Integer contractId
    }

    class Car {
        Integer id
        Integer ownerId
        Integer userId
        String type
        String brand
        String model
        Integer year
        String engineNumber
        String chassisNumber
        String serialNumber
        String vinNumber
        String ppu
        String status
        String adquisition_date
        String inscription
        String issuance_certificate
    }

    class CarDocuments {
        Integer id
        Integer vehicleId
        String type
    }

    class Contract {
        Integer id
        Integer userId
        Date initDate
        Date endDate
    }

    class ContractTerms {
        Integer contractId
        Integer termsId
    }
    
    class Operator {
        Integer id
        Integer userId
        String name
        String surname
        String dni
        String gender
    }

    class OperatorDocuments {
        Integer id
        Integer operatorId
        String type
    }

    class Organization { 
        String name
        OrganizationType type
    }

    class Owner {
        Integer id
        String name
        String username
        String address
        Integer commune
        Integer numeration
    }

    class PromotionsAssign {
        Integer id
        Integer promotionOwnerId
        Integer userId
    }

    class PromotionsOwner {
        Integer id
        Integer userId
        String name
        String qty
        Date initDate
        Date endDate
    }
  
    class Region {
        Integer id
        String name
    }

    class Commune {
        Integer id
        Integer regionId
        String name
    }

    class Role {
        Integer id
        String name
    }

    class Terms {
        Integer id
        Integer userId
        String key
        String value
    }

    class User {
        Integer id
        String username
        String password
        String email
        Integer RoleId
    }

    Organization "1" *-- "many" User
    User "1 or 0" *-- "many" Car
    note on link
        Solo los usuarios de empresas 
        transportistas pueden tener vehiculos
    endnote
    Owner "1" *-- "many" Car
    OrganizationType --> Organization
    note right on link
        Una organización debe ser de tipo
        empresa operadora o transportista
    endnote
    Region "1" *-- "many" Commune
    Commune "1" *-- "many" Owner
    Car "1" *-- "many or 0" Application
    Car "1" *-- "many or 0" CarDocuments
    User "1" *-- "many or 0" Contract
    Contract "1" *-- "many" Application
    Operator "1" *-- "many" Application
    Contract "1" *-- "many" ContractTerms
    Terms "1" *-- "many" ContractTerms
    Role "1" *-- "many" User
    Operator "1" *-- "many" OperatorDocuments
    User "1" *-- "many" Terms
    User "1" *-- "many or 0" PromotionsOwner
    User "1" *-- "many or 0" PromotionsAssign
    PromotionsOwner "1" *-- "many or 0" PromotionsAssign
    
@enduml